[package]
name = "toylanguage"
version = "0.1.0"
authors = ["Paavo Huhtala <paavo.huhtala@gmail.com>"]
edition = "2018"

[lib]
name = "toylang"
path = "src/lib.rs"

[[bin]]
name = "toylangi"
path = "src/main.rs"

[dependencies]

